---
execute:
  echo: false

format:
  html:
    embed-resources: true
    grid: 
      body-width: 1300px
---

# Pregled Bajs uporabe


```{python}
import pandas as pd
import numpy as np
import json
import folium
from datetime import datetime, timedelta
import os
import seaborn as sns
import matplotlib.pyplot as plt
import yaml

from data_cleaning.json_manipulation import load_json, trim_json_to_locations, gather_bajs_locations, get_bikes_in_stations, calculate_bike_changes, create_changes_columns
from visualization.station_map import populate_map_with_stations
from visualization.individual_station_plots import plot_hourly_bar, plot_weekday_bar, stringify_plot, combined_plot_daily_weekly
from data_cleaning.data_wrangling import create_hourly_df, create_weekday_df
```

```{python}
config = yaml.safe_load(open("../config.YAML"))
```

```{python}
raw_files_directory = "../data/" + config["data"]["raw_json_folder"]

raw_files = os.listdir(raw_files_directory)
```


```{python}
scraped_datetimes = [datetime.strptime(filename[5:-5], "%d-%m-%Y_%H-%M-%S") for filename in raw_files]

# vrijeme prilikom preuzimanja je 1 sat ranije nego aktualno vrijeme u ZG, sređujemo ovdje
scraped_datetimes = [date + timedelta(hours = 1) for date in scraped_datetimes]
```


```{python}
data_timepoints = [
    trim_json_to_locations(load_json(raw_files_directory + "/" + json_file))
    for json_file
    in raw_files
]
```

```{python}
# Formatting everything into a single dataframe
bike_data = None

for i in range(len(data_timepoints)):
    timepoint_bikes = get_bikes_in_stations(time = scraped_datetimes[i],
        loc_list = data_timepoints[i])

    if i == 0: 
        bike_data = timepoint_bikes
    else:
        bike_data = pd.concat([bike_data, timepoint_bikes])
```
```{python}
# Dataframe gdje je svaki redak jedna postaja u jednoj točki mjerenja
bike_data = create_changes_columns(bike_data)
```

```{python}
dates = bike_data["time"].sort_values()
first_date = datetime.date(dates.iloc[0])
last_date = datetime.date(dates.iloc[-1])

no_days = (last_date - first_date).days
```

```{python}
# Info o postajama, na temelju posljednjeg dohvata podataka
locations = gather_bajs_locations(data_timepoints[-1])
```

```{python}
# Ukupni broj korištenja za svaku postaju

total_changes = bike_data.groupby("uid").sum(["changes", "outgoing", "incoming"])
total_changes = total_changes.rename({"changes":"total_changes"}, axis = 1)
```


```{python}
# Prosječni broj korištenja po danu, + težinski prosjek s obzirom na broj mjesta za bicikle
# Realnim korištenjem smatramo ODLASKE sa stanica! Brojanje i dolazaka i odlazaka nam zapravo
# duplira realan broj vožnji

locations_changes = locations.join(total_changes, on = "uid")
locations_changes["daily_avg"] = locations_changes["outgoing"] / no_days
locations_changes["weighted_changes"] = locations_changes["daily_avg"] / locations_changes["no_racks"]
```

```{python}

# zaokruži na dvije decimale za prikaz u tablicama i na karti
locations_changes["daily_avg"] = np.round(locations_changes["daily_avg"], 2)
locations_changes["weighted_changes"] = np.round(locations_changes["weighted_changes"], 2)
```

```{python}
# ukupni izračuni za sve postaje zajedno
dnevni_prosjek_koristenja = np.sum(locations_changes["daily_avg"])
ukupno_postaja = locations_changes.shape[0]
ukupno_mjesta_za_bicikle = np.sum(locations_changes["no_racks"])

dnevni_prosjek_po_postaji = dnevni_prosjek_koristenja / ukupno_postaja
dnevni_prosjek_po_mjestu_za_bajs = dnevni_prosjek_koristenja / ukupno_mjesta_za_bicikle
```

Na temelju dohvata javno dostupnih podataka o stanju Bajs postaja u Zagrebu provedena je analiza kako bi se utvrdili obrasci o korištenju Bajs bicikala. Podaci su prikupljeni u razdoblju od `{python} first_date.strftime("%d.%m.%Y.")` do `{python} last_date.strftime("%d.%m.%Y.")`, što obuhvaća ukupno `{python} no_days` dana.  
U trenutku provođenja analize u Zagrebu je bilo postavljeno `{python} int(ukupno_postaja)` postaja. U ovom dokumentu prikazat će se podaci o ukupnom korištenju bicikala, izdvojene postaje, te interaktivna karta s pregledom popularnosti postaja te opaženih trendova korištenja kroz sate u danu i dane u tjednu.

Pojam "*korištenje*" bicikla ovdje označava da je bicikl bio odvezen sa određene postaje. Dolasci na postaju se prikazuju samo u određenim dijelovima dokumenta, poput prikaza prosječne aktivnosti postaja po satima u danu u interaktivnoj mapi.

## Ukupno korištenje Bajseva


Gledajući ukupno korištenje Bajseva za sve postaje u Zagrebu, prosječno se bajsevi dnevno koriste `{python} int(dnevni_prosjek_koristenja)` puta. Postavljeno je `{python} int(ukupno_postaja)` postaja s ukupno `{python} int(ukupno_mjesta_za_bicikle)` mjesta za bicikle.  
Prosječno se na svakoj postaji bajsovi koriste `{python} round(float(dnevni_prosjek_po_postaji),2)` puta dnevno, odnosno `{python} round(float(dnevni_prosjek_po_mjestu_za_bajs),2)` puta dnevno po svakom mjestu (engl. *rack*) za bicikle.


U nastavku je prikazan prosječan broj korištenja po satima u danu, po čemu se mogu vidjeti razdoblja najveće i najmanje aktivnosti. Stupac kod određenog sata znači da se u razdoblju od sat vremena unatrag opazilo toliko korištenja (npr. stupac kod sata 10 označava razdoblje 9:01-10:00).  

```{python}
#| fig-align: "center"
po_satu = create_hourly_df(bike_data).groupby(["hour"]).sum()

po_danu = create_weekday_df(bike_data).groupby(["wday"]).sum()

_ = plot_hourly_bar(po_satu, changes_type = "out")
```

Na sljedećoj slici prikazane su varijacije u korištenju bicikala ovisno o danu u tjednu.

```{python}
#| fig-align: "center"
_ = plot_weekday_bar(po_danu)
```

Pri kraju dokumenta nalazi se interaktivna mapa postaja na kojoj je klikom na određenu postaju moguće dobiti ovakve grafikone napravljene specifično za nju. Tako je moguće vidjeti trendove korištenja upravo za one relacije koje su čitatelju najrelevantnije.  

## Postaje  

```{python}
# tablice za prikaz - izmjene u nazivima stupaca
postaje_prikaz = locations_changes
postaje_prikaz = postaje_prikaz.rename(columns={
    "name" : "Ime postaje",
    "no_racks" : "Mjesta za bickle",
    "daily_avg" : "Korištenja dnevno",
    "weighted_changes" : "Dnevno korištenja po mjestu za bicikle"
})

postaje_prikaz = postaje_prikaz[["Ime postaje", "Mjesta za bickle", "Korištenja dnevno", "Dnevno korištenja po mjestu za bicikle"]]
```

U nastavku su navedene tri tablice s podacima o postajama. Kao kratki pregled aktivnosti cijelog sustava zanimljivo je vidjeti koje su postaje najaktivnije.  

Najviše korištene postaje:

```{python}
postaje_prikaz.sort_values("Korištenja dnevno",  ascending = False).head(10)
```

Još jedan oblik aktivnosti je prosječan dnevni broj korištenja podijeljen s brojem mjesta za bicikle na određenoj postaji. Visok rezultat na ovoj mjeri može označavati da su određene postaje prenapučene, odnosno da je potražnja za Bajs biciklima potencijalno veća nego što ponuđeni broj dostupnih bicikala trenutno može zadovoljiti. Te su postaje potencijalni kandidati za proširenje povećanjem broja dostupnih bicikala.   

Najviše korištene postaje s obzirom na broj mjesta za bickle:

```{python}
postaje_prikaz.sort_values("Dnevno korištenja po mjestu za bicikle",  ascending = False).head(10)
```

U sljedećoj tablici navedene su postaje na kojima je zabilježena najmanja aktivnost. Za ove je postaje korisno istražiti koji su mogući uzroci manjka aktivnosti. Neki su očekivani i na njih se ne može sustavno utjecati; na primjer, postaje u područjima male gustoće naseljenosti vjerojatno će imati i manji broj korištenja od onih gdje veći broj ljudi obitava ili radi. Mogući su i uzroci na koje se može utjecati izmjenama u sustavu Bajsa; na primjer, moguće je da su određene postaje fizički previše udaljene od svojih prvih susjeda pa stanovnicima nije praktično uskladiti svoje svakodnevne rute oko dostupnih postaja.

Najmanje korištene postaje:

```{python}
postaje_prikaz.sort_values("Korištenja dnevno",  ascending = True).head(10)
```

## Interaktivna mapa postaja

Prelaskom preko svake postaje prikazuje se prosječni dnevni broj korištenja bicikala i broj mjesta za bicikle. Klikom na postaju prikazuju se grafikoni s informacijama o prosječnom korištenju za svaki sat u danu i za svaki dan u tjednu.  
Kod prikaza po satima moguće je vidjeti broj korištenja bicikala s ove postaje ("*Odlazni*" u grafikonu), kao i kada se najviše bicikala ostavlja na ovoj postaji ("*Dolazni*" u grafikonu).  


```{python}
hourly = create_hourly_df(bike_data)
weekdaily = create_weekday_df(bike_data)
```


```{python}
fig = folium.Figure(width = 1100, height = 500)

m = folium.Map(
    location=(45.8109, 16.0097),
    min_zoom=11,
    tiles = "Esri.WorldTopoMap"
)

fig.add_child(m)

circles = populate_map_with_stations(m,
                               locations_changes, 
                               metric_size = "daily_avg", 
                               metric_tooltip_name = "Prosječno dnevno korištenje bicikala: ",
                               no_bins = 35)
```


```{python}
for i in range(len(circles)):
    circ = circles[i]

    station_uid = locations_changes["uid"].iloc[i]

    circ.add_child(folium.Popup(stringify_plot(
        combined_plot_daily_weekly(hourly.loc[station_uid], weekdaily.loc[station_uid])[0]
        )))

_ = [circ.add_to(m) for circ in circles]
```


```{python}
#| body-width: 100%
m
```

# Ograničenja
Podaci za ovaj dokument dohvaćaju se na razini jednog sata. Zbog toga se ne bilježe sve promjene u lokaciji bicikala unutar pojedinog sata. Drugim riječima, stvaran broj korištenja bicikala je vjerojatno **veći** od onog navedenog u ovom dokumentu.  
Ipak, osnovna namjena ove analize je prikazati trendove korištenja, a oni su vrlo vjerojatno postojani čak i ako se podaci ne dohvaćaju u realnom vremenu. Informacije o tome koje su postaje najviše i najmanje korištene te koji sati ili dani u tjednu pokazuju najveću aktivnost vrlo vjerojatno ne bi bile drugačije uz veću razinu detalja pri prikupljanju podataka.  

Ono što se mijenja je apsolutni broj korištenja: Možda se za neku postaju trenutno navodi da se koristi 100 puta dnevno, a stvarno stanje je 130 jer je u nekim satima isti bicikl dovezen na postaju i odmah preuzet i odvezen dalje.  
Ova pristranost je manja za manje korištene postaje: Ako su veći broj sati zaredom opaženi isti bicikli na istoj postaji znači da tu nije došlo do nikakvih promjena, te bi to vrijedilo jednako i da se podaci dohvaćaju mnogo češće od jednom na sat.  
